### ISSUE TITLE
wanted: binary Windows releases

### ISSUE THREAD

**Issue by c33s** [curl/trurl#130]
it would be nice to have binary releases on github (including windows). for golang tools it is quite common that they provide multiplatform builds on github.

**Comment by bagder** [comment]
If someone wants to work on that I'll help out, but it's not a priority for me personally.

**Comment by bagder** [comment]
lots of distros [already ship trurl](https://github.com/curl/trurl/discussions/51).

**Comment by c33s** [comment]
having a official windows binary would still be a thing

**Comment by bagder** [comment]
Agreed. It would be great if someone provided such.

**Comment by fragolinux** [comment]
@bagder i started working on this a few days ago, but had no time to go on... if you want to [take a look](https://github.com/fragolinux/trurl/tree/master/.github/workflows)... it builds, but both files should be merged in a single one using matrix, so there will be a single final release, with all the artifacts generated and attached to it... right now, the fastest build will push the binary and create release, the slowest follows and halts overwriting the other built one (different arch), and cannot create a new release because it already exists...

**Comment by bagder** [comment]
I would presume that for Linux and macOS this is less interesting than for Windows.

**Comment by fragolinux** [comment]
> I would presume that for Linux and macOS this is less interesting than for Windows.

why? Having binaries instead of just sources published on releases page would allow to release an asdf plugin, too, to have this versioned

**Comment by c33s** [comment]
i also think that having official binaries for all platforms is good thing. being able to simply wget the binary with the latest version from the official source is so nice. not having to wait for third parties until they update their packages or fiddle around with docker. one of the main reasons i meanwhile narrow my search to golang for small cli tools (sometimes rust too) - they offical sources ship binaries.

**Comment by bagder** [comment]
If someone wants to provide builds for *any* platform, feel free to work on it.

**Comment by fragolinux** [comment]
> If someone wants to provide builds for _any_ platform, feel free to work on it.

@bagder [done](https://github.com/curl/trurl/pull/177)! :D 
example release: https://github.com/fragolinux/trurl/releases/tag/v0.6.0

**Comment by vszakats** [comment]
I've added trurl to curl-for-win. For now I did not enable it in the live releases,
but if we agree that this would be desired, it's certainly possible. Let me know.

They are already present in the daily curl-for-win builds:
https://github.com/curl/curl-for-win/actions/workflows/daily.yml

**Comment by vszakats** [comment]
Windows builds are running now in CI.

For release purposes it may use a slightly different configuration, for a bit smaller binaries with longer build times. Otherwise the existing CI logic can be re-used for this Issue almost as-is. The question is where to upload the result, how to trigger it and adding the necessary logic for these.

It would be a better way to distribute trurl than adding them to the official curl package. The latter features shared `trurl.exe` (~40KB), while the ones here are building a static `trurl.exe` with a thin libcurl, making it 350-400KB per `.exe`.

**Comment by vszakats** [comment]
After another round of optimizations with trurl builds, the size of the reference Windows ARM64 `turl.exe` is down to 89KB with IMAP, and 53KB without. Can use "unity" mode now without side-effects on build size. It means the existing CI process can be reused as-is for live builds.

**Comment by vszakats** [comment]
Either the thing suggested in the last comment could be used to pull this off, though it'd be a new process and someone needs do it. It could probably be done with in GHA with results uploaded to the Release page. (I have no recipes ready for this.)

Or, to avoid the extra work, it's possible to enable trurl in official curl-for-win builds. In such case, it'd be using the existing curl/libcurl build process, which builds a "universal" libcurl lib (= not specifically optimized for trurl, meaning much larger in size). This would make a static `trurl.exe` almost as large as `curl.exe`. It means it's only practical to link to `libcurl.dll`. Which in practice means that the curl-for-win binary directory needs to be added to the `PATH` or both `libcurl.dll` and `trurl.exe` copied to a directory `PATH`. This breaks the static promise of the curl-for-win distribution, but may be an acceptable compromise.

`turl.exe` has been included that way in the 'daily' curl-for-win builds for quite a while now:
https://github.com/curl/curl-for-win/actions/workflows/daily.yml

**Comment by bagder** [comment]
Thanks @vszakats, I think we can live with getting it from the the curl-for-win daily builds until someone provides something else.
